# Generated by Django 5.0.4 on 2024-04-17 00:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_event', models.CharField(max_length=255, verbose_name='Event Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('music', 'Music'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('conference', 'Conference'), ('workshop', 'Workshop'), ('other', 'Other')], max_length=50, verbose_name='Category')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('cancelled', 'Cancelled')], max_length=20, verbose_name='Status')),
                ('image', models.ImageField(upload_to='event_images/', verbose_name='Imagem')),
                ('ticket_quantity', models.IntegerField(verbose_name='Ticket Quantity')),
                ('tickets_sold', models.IntegerField(blank=True, null=True, verbose_name='Tickets Sold')),
                ('tickets_available', models.IntegerField(null=True, verbose_name='Tickets Available')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_address', to='address.address')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
