# Generated by Django 5.0.4 on 2024-04-18 14:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do evento')),
                ('date', models.DateField(verbose_name='Data')),
                ('time', models.TimeField(verbose_name='Horário')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('category', models.CharField(choices=[('music', 'Música'), ('sports', 'Esportes'), ('entertainment', 'Entretenimento'), ('conference', 'Conferência'), ('workshop', 'Workshop'), ('other', 'Outros')], max_length=50, verbose_name='Categoria')),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('cancelled', 'Cancelado'), ('concluded', 'Concluído')], max_length=20, verbose_name='Status')),
                ('image', models.ImageField(upload_to='events', verbose_name='Banner')),
                ('ticket_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do ingresso')),
                ('half_ticket_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Meia entrada')),
                ('ticket_quantity', models.IntegerField(verbose_name='Quantidade de ingressos')),
                ('tickets_sold', models.IntegerField(default=0, verbose_name='Quantidade de ingressos vendidos')),
                ('tickets_available', models.IntegerField(verbose_name='Quantidade de ingressos disponíveis')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_address', to='address.address', verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
