# Generated by Django 5.0.4 on 2024-04-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='half_ticket_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de ingressos do tipo meia-entrada'),
        ),
        migrations.AddField(
            model_name='event',
            name='half_tickets_available',
            field=models.IntegerField(null=True, verbose_name='Quantidade de ingressos disponíveis do tipo meia-entrada'),
        ),
        migrations.AlterField(
            model_name='event',
            name='half_ticket_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do ingresso do tipo meia-entrada'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_quantity',
            field=models.IntegerField(verbose_name='Quantidade de ingressos do tipo inteira'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do ingresso do tipo inteira'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tickets_available',
            field=models.IntegerField(verbose_name='Quantidade de ingressos disponíveis do tipo inteira'),
        ),
    ]
