# Generated by Django 5.0.4 on 2024-08-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_hero_event',
            field=models.BooleanField(blank=True, default=False, verbose_name='Evento em destaque principal na Hero Section'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_top_event',
            field=models.BooleanField(blank=True, default=False, verbose_name='Evento em destaque'),
        ),
    ]
