# Generated by Django 5.0.4 on 2024-08-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_is_hero_event_event_is_top_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='half_ticket_quantity',
            field=models.IntegerField(blank=True, default=0, verbose_name='Quantidade de ingressos do tipo meia-entrada'),
        ),
        migrations.AlterField(
            model_name='event',
            name='half_ticket_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Valor do ingresso do tipo meia-entrada'),
        ),
    ]
