# Generated by Django 5.0.4 on 2024-08-30 21:38

import apps.events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_options_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to=apps.events.models.event_image_upload_to, verbose_name='Banner'),
        ),
    ]
