# Generated by Django 5.0.4 on 2024-05-06 17:46

import apps.core.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('token', models.CharField(max_length=100)),
                ('transaction_amount', models.FloatField()),
                ('installments', models.IntegerField()),
                ('payment_method_id', models.CharField(max_length=100)),
                ('issuer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payer_first_name', models.CharField(max_length=100)),
                ('payer_email', models.EmailField(max_length=254)),
                ('payer_identification_type', models.CharField(max_length=100)),
                ('payer_identification_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('in_process', 'In process'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('charged_back', 'Charged back')], default='pending', max_length=100)),
                ('status_detail', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(apps.core.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(apps.core.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
