# Generated by Django 5.0.4 on 2024-04-23 17:22

import apps.utils.cpf_cnpj.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=apps.utils.cpf_cnpj.models.CPFField(max_length=11, verbose_name='CPF'),
        ),
    ]
