# Generated by Django 5.0.4 on 2024-08-15 13:40

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(default=datetime.date(2000, 1, 1), validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Homem'), ('F', 'Mulher'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=12, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='birthdate',
            field=models.DateField(default=datetime.date(2000, 1, 1), validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Homem'), ('F', 'Mulher'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='phone',
            field=models.CharField(max_length=12, null=True, verbose_name='Telefone'),
        ),
    ]
