# Generated by Django 5.0.4 on 2024-08-20 23:52

import apps.utils.cpf_cnpj.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_birthdate_alter_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cnpj',
            field=apps.utils.cpf_cnpj.models.CNPJField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='cnpj',
            field=apps.utils.cpf_cnpj.models.CNPJField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
    ]
