# Generated by Django 5.0.4 on 2024-04-29 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
        ('tickets', '0002_add_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_purchase', to='financial.purchase', verbose_name='Compra'),
        ),
    ]
