# Generated by Django 5.0.4 on 2024-08-26 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_remove_historicalpurchase_created_by_and_more'),
        ('tickets', '0003_ticket_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='purchase',
        ),
        migrations.AddField(
            model_name='ticket',
            name='cart_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_card_payments', to='financial.cartpayment', verbose_name='Compra'),
        ),
    ]
