# Generated by Django 5.0.4 on 2024-05-15 20:58

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='id_user',
            new_name='user',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('external_id', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='ID externo')),
                ('payment_type', models.CharField(choices=[('PIX', 'Pix'), ('CREDIT_CARD', 'Cartão de crédito')], max_length=50, verbose_name='Tipo do pagamento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('RECEIVED', 'Recebido'), ('CONFIRMED', 'Confirmado'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=50, verbose_name='Status')),
                ('link_payment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link do pagamento')),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(apps.core.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='financial.purchase')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(apps.core.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
