# Generated by Django 5.0.4 on 2024-08-26 19:05

import apps.core.models
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_historicalpayment_historicalpurchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpurchase',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalpurchase',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpurchase',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalpurchase',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.CreateModel(
            name='CartPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('external_id', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='ID externo')),
                ('payment_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo do pagamento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmado')], default='PENDING', max_length=50, verbose_name='Status')),
                ('link_payment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link do pagamento')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor total')),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(apps.core.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(apps.core.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalCartPayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated at')),
                ('external_id', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='ID externo')),
                ('payment_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo do pagamento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmado')], default='PENDING', max_length=50, verbose_name='Status')),
                ('link_payment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link do pagamento')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor total')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical cart payment',
                'verbose_name_plural': 'historical cart payments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='HistoricalPayment',
        ),
        migrations.DeleteModel(
            name='HistoricalPurchase',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
