# Generated by Django 5.0.4 on 2024-08-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_remove_historicalpurchase_created_by_and_more'),
        ('tickets', '0004_remove_ticket_purchase_ticket_cart_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
