# Generated by Django 5.0.4 on 2024-09-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_alter_cartpayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('RECEIVED', 'Recebido')], default='PENDING', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalcartpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('RECEIVED', 'Recebido')], default='PENDING', max_length=50, verbose_name='Status'),
        ),
    ]
