# Generated by Django 5.0.4 on 2024-08-30 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_address_complement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
    ]
